package bikerental.model;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Booking {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Long userId;

    private String customerName;

    private String phone;

    private Long bikeId;

    private String bikeName;

    /*
     * Pickup date:
     * YYYY-MM-DD
     */
    private String date;

    /*
     * HOURLY or DAILY
     *
     * Existing old bookings may have null here.
     * Backend will later treat old/null bookings as DAILY.
     */
    private String rentalType;

    /*
     * Used only for HOURLY bookings.
     *
     * Format:
     * HH:mm
     *
     * Example:
     * 10:30
     */
    private String pickupTime;

    /*
     * Used for DAILY rental.
     *
     * Example:
     * 1, 2, 3 ... 30
     */
    private Integer durationDays;

    /*
     * Used for HOURLY rental.
     *
     * Allowed later:
     * 1 to 12 hours
     */
    private Integer durationHours;

    /*
     * Price snapshots.
     *
     * We save the price that existed when
     * the customer created the booking.
     */
    private double pricePerDay;

    private Double pricePerHour;

    private double totalAmount;

    /*
     * Actual calculated booking interval.
     *
     * These are generated by the backend,
     * not trusted from frontend input.
     *
     * Used for slot-conflict checking.
     */
    private LocalDateTime startDateTime;

    private LocalDateTime endDateTime;

    /*
     * PENDING
     * APPROVED
     * REJECTED
     * COMPLETED
     */
    private String status;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Long getBikeId() {
        return bikeId;
    }

    public void setBikeId(Long bikeId) {
        this.bikeId = bikeId;
    }

    public String getBikeName() {
        return bikeName;
    }

    public void setBikeName(String bikeName) {
        this.bikeName = bikeName;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getRentalType() {
        return rentalType;
    }

    public void setRentalType(String rentalType) {
        this.rentalType = rentalType;
    }

    public String getPickupTime() {
        return pickupTime;
    }

    public void setPickupTime(String pickupTime) {
        this.pickupTime = pickupTime;
    }

    public Integer getDurationDays() {
        return durationDays;
    }

    public void setDurationDays(Integer durationDays) {
        this.durationDays = durationDays;
    }

    public Integer getDurationHours() {
        return durationHours;
    }

    public void setDurationHours(Integer durationHours) {
        this.durationHours = durationHours;
    }

    public double getPricePerDay() {
        return pricePerDay;
    }

    public void setPricePerDay(double pricePerDay) {
        this.pricePerDay = pricePerDay;
    }

    public Double getPricePerHour() {
        return pricePerHour;
    }

    public void setPricePerHour(Double pricePerHour) {
        this.pricePerHour = pricePerHour;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    public LocalDateTime getStartDateTime() {
        return startDateTime;
    }

    public void setStartDateTime(LocalDateTime startDateTime) {
        this.startDateTime = startDateTime;
    }

    public LocalDateTime getEndDateTime() {
        return endDateTime;
    }

    public void setEndDateTime(LocalDateTime endDateTime) {
        this.endDateTime = endDateTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}